services:
  postgres:
    container_name: postgres_container
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      backend

  order:
  product:


networks:
  backend:
type: bridge