name: Java CI pipeline e-come

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - uses: actions/checkout@v4
#
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-services: ${{ steps.detect.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Find modified services
        id: detect
        run: |
          # Если это первый коммит в репозитории, проверяем все сервисы
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "First commit in the repo, building all services."
            echo "changed=$(echo "config-server" | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Для обычных коммитов используем git diff
          if [ "$GITHUB_BASE_REF" != "" ]; then
            # Для Pull Request сравниваем с веткой назначения
            CHANGED_FILES=$(git diff --name-only $GITHUB_BASE_REF...HEAD)
          else
            # Для обычного push сравниваем с предыдущим коммитом
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          fi

          # Проверяем, какие сервисы затронуты
          CHANGED_SERVICES=()
          for SERVICE in config-server; do
            if echo "$CHANGED_FILES" | grep -q "^services/$SERVICE/"; then
              CHANGED_SERVICES+=("$SERVICE")
            fi
          done

          # Если изменились docker-compose.yml или файлы CI, собираем всё
          if [ ${#CHANGED_SERVICES[@]} -eq 0 ] && echo "$CHANGED_FILES" | grep -qE "^(docker-compose.yml|\.github/workflows/)"; then
            CHANGED_SERVICES=("config-server")
          fi

          # Если изменений нет (например, обновили README), пропускаем сборку
          if [ ${#CHANGED_SERVICES[@]} -eq 0 ]; then
            echo "No relevant changes detected, skipping build."
            exit 0
          fi

          # Передаём список изменённых сервисов в выходные данные
          echo "changed=$(echo "${CHANGED_SERVICES[@]}" | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT

  build-changed:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed-services != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.changed-services) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          ########## my piece ######################################################################
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          ################################################################################
      - name: Build ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: ./gradlew clean bootJar