name: Java CI pipeline e-come

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-services: ${{ steps.detect.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find modified services
        id: detect
        run: |
          # Автоматически определяем все сервисы в папке services/
          ALL_SERVICES=$(ls -d services/*/ | cut -d'/' -f2)
          
          # Если это первый коммит в репозитории, проверяем все сервисы
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "First commit in the repo, building all services."
            echo "changed=$(echo "$ALL_SERVICES" | jq -R -s -c 'split("\n") | map(select(. != ""))')" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Для обычных коммитов используем git diff
          if [ "$GITHUB_BASE_REF" != "" ]; then
            # Для Pull Request сравниваем с веткой назначения
            CHANGED_FILES=$(git diff --name-only $GITHUB_BASE_REF...HEAD)
          else
            # Для обычного push сравниваем с предыдущим коммитом
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          fi

          # Проверяем, какие сервисы затронуты
          CHANGED_SERVICES=()
          for SERVICE in $ALL_SERVICES; do
            if echo "$CHANGED_FILES" | grep -q "^services/$SERVICE/"; then
              CHANGED_SERVICES+=("$SERVICE")
            fi
          done

          # Если изменились общие файлы, собираем всё
          if [ ${#CHANGED_SERVICES[@]} -eq 0 ] && \
             echo "$CHANGED_FILES" | grep -qE "^(docker-compose\.yml|\.github/workflows/|gradle\.properties|build\.gradle)"; then
            CHANGED_SERVICES=($ALL_SERVICES)
          fi

          # Если изменений нет (например, обновили README), пропускаем сборку
          if [ ${#CHANGED_SERVICES[@]} -eq 0 ]; then
            echo "No relevant changes detected, skipping build."
            exit 0
          fi

          # Передаём список изменённых сервисов в выходные данные
          echo "changed=$(echo "${CHANGED_SERVICES[@]}" | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT

  build-changed:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed-services != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.changed-services) }}
    steps:
      - uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Services directory content:"
          ls -la services/
          echo "Target service directory content:"
          ls -la services/${{ matrix.service }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            services/${{ matrix.service }}/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ matrix.service }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ matrix.service }}
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        working-directory: ./services/${{ matrix.service }}
        run: |
          if [ -f "gradlew" ]; then
            chmod +x gradlew
          else
            echo "gradlew not found"
          fi

      - name: Build ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: ./gradlew clean bootJar