name: Java CI pipeline e-come

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-services: ${{ steps.detect.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find modified services
        id: detect
        run: |
          ALL_SERVICES=$(ls -d services/*/ | cut -d'/' -f2 | tr '\n' ' ')
          
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "changed=$(echo "$ALL_SERVICES" | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [ "$GITHUB_BASE_REF" != "" ]; then
            CHANGED_FILES=$(git diff --name-only $GITHUB_BASE_REF...HEAD)
          else
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          fi

          CHANGED_SERVICES=()
          for SERVICE in $ALL_SERVICES; do
            if echo "$CHANGED_FILES" | grep -q "^services/$SERVICE/"; then
              CHANGED_SERVICES+=("$SERVICE")
            fi
          done

          if [ ${#CHANGED_SERVICES[@]} -eq 0 ] && \
             echo "$CHANGED_FILES" | grep -qE "^(docker-compose\.yml|\.github/workflows/|gradle\.properties|build\.gradle)"; then
            CHANGED_SERVICES=($ALL_SERVICES)
          fi

          if [ ${#CHANGED_SERVICES[@]} -eq 0 ]; then
            echo "No relevant changes detected, skipping build."
            exit 0
          fi

          echo "changed=$(echo "${CHANGED_SERVICES[@]}" | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT

  build-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed-services != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.changed-services) }}
    steps:
      - uses: actions/checkout@v4

      - name: Verify service directory
        id: verify-dir
        run: |
          SERVICE_DIR="services/${{ matrix.service }}"
          echo "Checking directory: $SERVICE_DIR"
          if [ ! -d "$SERVICE_DIR" ]; then
            echo "::error::Directory $SERVICE_DIR does not exist!"
            ls -la services/ || true
            exit 1
          fi
          echo "Directory exists. Contents:"
          ls -la "$SERVICE_DIR"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            services/${{ matrix.service }}/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ matrix.service }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ matrix.service }}
            ${{ runner.os }}-gradle-

      - name: Prepare Gradle Wrapper
        run: |
          cd "services/${{ matrix.service }}"
          if [ ! -f "gradlew" ]; then
            echo "::error::gradlew not found in services/${{ matrix.service }}"
            ls -la || true
            exit 1
          fi
          chmod +x gradlew
          ./gradlew --version

      - name: Build with Gradle
        run: |
          cd "services/${{ matrix.service }}"
          ./gradlew clean bootJar