name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-dir: [ "config-server" ]  # Укажи свои сервисы
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        shell: bash
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build and Test
        working-directory: ./services/${{ matrix.service-dir }}
        run: ./gradlew build